### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by techwithanirudh** [newsnowlabs/dockside#18]
There are no updates of this project for a month.

**Comment by struanb** [comment]
Certainly not. We've been working on the next major update, which will be released soon.

**Comment by techwithanirudh** [comment]
@struanb That is awesome! Sorry for the misunderstanding!

**Comment by techwithanirudh** [comment]
@struanb Is there an ETA, if so that'd be great!

**Comment by struanb** [comment]
Just putting finishing touches to the release, so hopefully in the next week or so. 🤞

**Comment by techwithanirudh** [comment]
> Just putting finishing touches to the release, so hopefully in the next week or so. 🤞

@struanb Any updates?

**Comment by struanb** [comment]
@techwithanirudh We've pushed the latest code and docs to https://github.com/newsnowlabs/dockside/tree/devel-ssh-prerelease and built a prerelease Docker image, `newsnowlabs/dockside:devel-ssh-prerelease`.

This prerelease is essentially commit https://github.com/newsnowlabs/dockside/commit/8a94c67737d9a584df220b4403a1ba0ac1dc4333:
```
Integrated SSH server support
- Provisions an SSH and a wstunnel daemon for each devtainer allowing
  any authorised developer to SSH in
- Maintenance of `~/.ssh/authorized_keys` file for the devtainer owner
  and other developers with whom the devtainer is shared
- One-click SSH from the Dockside UI
- wstunnel helper setup instructions integrated in the Dockside UI
- Facilitates use of any terminal editor or command line tool including
  those that benefit from key forwarding, such as `git`;
- Facilitates seamless
  [VS Code remote development](https://code.visualstudio.com/docs/remote/ssh)
  via the
  [Remote SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh)
  extension.

Dockside now enables SSH by default for all new devtainers.
```

If you'd like to try it, follow the install instructions in the [README on the prerelease branch](https://github.com/newsnowlabs/dockside/tree/devel-ssh-prerelease) (the `docker run` command has changed slightly), substituting this prerelease image name `newsnowlabs/dockside:devel-ssh-prerelease` for `newsnowlabs/dockside` in your `docker run` command.

For instructions on enabling, configuring, disabling SSH and technical details, see
https://github.com/newsnowlabs/dockside/blob/devel-ssh-prerelease/docs/extensions/ssh.md.

Good luck, and please advise if you run into any difficulties.
