### ISSUE TITLE
Fix issue with GitLens extension not working

### ISSUE THREAD

**Issue by MarkFitzpatrickNN** [newsnowlabs/dockside#20]
Currently GitLens is not working. Previously this was working as expected but stopped since the update of theia to version 1.40.

## Replication steps

1. Open a new devtainer
2. Go to the extensions tab
3. Search for GitLens
4. Click install
5. The gitlens tab will automatically be open but be missing its icon.
6. An error will appear when you hover over the tab saying something similar to … server IP address could not be found.

![Screenshot 2023-10-09 at 11 42 15](https://github.com/newsnowlabs/dockside/assets/107934853/11dd869d-8685-4887-9cc3-1654759f909c)

**Comment by struanb** [comment]
As we believe this issue is actually fixed in the latest release of Dockside, we are closing this.
