### ISSUE TITLE
Built-in SSL cert is expired

### ISSUE THREAD

**Issue by paisley** [newsnowlabs/dockside#5]
### Run dockside using the build in cert

```
mkdir -p ~/.dockside && \
docker run -it --name dockside \
  -v ~/.dockside:/data \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -p 443:443 -p 80:80 \
  --security-opt=apparmor=unconfined \
  newsnowlabs/dockside --ssl-builtin
```

### Visit Dockside in web browser
Open Chrome and navigate to https://www.local.dockside.dev/

![expired-cert](https://user-images.githubusercontent.com/72166740/189796404-71f7b51d-1736-422b-bf3d-443a0dd51e4b.png)

**Comment by struanb** [comment]
@paisley We've now pushed a new Docker image now with an updated built-in certificate. If you have a chance to confirm this fixes the issue, please let us know.

(By way of explanation, the certificate renewal process was working, but the process for embedding it in the image and pushing the image was not. We will aim to fix this before the current certificate expires on 22 October 2022, and if we can't we'll update the image manually before that date).

**Comment by struanb** [comment]
This issue has been permanently resolved in the latest release of Dockside, in which the `*.local.dockside.dev` SSL certificate is downloaded on launch from a public cloud storage bucket.

https://github.com/newsnowlabs/dockside/releases/tag/v2.0.0
