### ISSUE TITLE
Using dockside behind an http proxy

### ISSUE THREAD

**Issue by vlacour97** [newsnowlabs/dockside#6]
I feel like it's impossible as it stands to use dockside behind an HTTP proxy.
I use a HAProxy to distribute the load of my applications according to the urls that I call and I have this error..
![image](https://user-images.githubusercontent.com/10577568/206750197-6f84e6d8-17d8-45b0-83e0-b28a4b4e8bc0.png)
But the called url is in https
Could the problem be corrected plz ?

**Comment by struanb** [comment]
Hi @vlacour97. Thanks for raising this issue, and apologies for the long delay in responding.

You are quite correct that running Dockside behind a proxy is currently unsupported. Dockside is intended to be accessed via HTTPS for security reasons (access to code and hardware) and so currently expects to terminate SSL connections itself.

It is _possible_ that an external proxy could be placed ahead of Dockside's internal proxy, and that this external proxy be used to terminate SSL connections instead. However Dockside's internal proxy/router is though highly opinionated about what URIs it expects to receive (and over multiple domains) - so it can route requests to the UI or to the right container - and so the external proxy would need very careful configuration to ensure all conceivable Dockside URIs were forwarded. There may be other unforeseen issues that would need resolving.

To the specific error you received, it looks like you have tried to forward a plain HTTP request to Dockside's HTTPS port. If this were to work at all, you would need to proxy from external HTTPS to Dockside's HTTPS port, and from external HTTP to Dockside's HTTP port.

I hope this helps. I will close this issue for now but feel free to reopen if we can assist further.
