### ISSUE TITLE
Nginx warning "ssl" directive is deprecated 

### ISSUE THREAD

**Issue by rohansukhdeo** [newsnowlabs/dockside#7]
Hello, when trying to start the container for dockside, I get this warning which is hindering me from seeing the auto-generated password to login to dockside:

dockside     | 2022-12-14.18:25:28.373153|00001| Launching s6 service supervisor ...
dockside     | 2022-12-14.18:25:28.379530|00001| >>> If running in a terminal, detach Dockside by typing: 
dockside     | 2022-12-14.18:25:28.382716|00001| >>> Navigate to https://www.local.dockside.dev/
dockside     | 2022-12-14.18:25:28.414691|00162| Launching nginx
**dockside     | nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /home/newsnow/dockside/app/server/nginx/conf/sites-available/default:136**

Can you please advise on how to get around this so that I can see the auto-generated password in the terminal and log into dockside. Thank you!

**Comment by struanb** [comment]
Hi @rohansukhdeo. Apologies for the long delay in getting back to you on this issue. We have been affected by illness in our team. This issue has been fixed in the latest release: https://github.com/newsnowlabs/dockside/releases/tag/v2.2.0.

Please try it out!
